### PR TITLE
Add image_optim to gh-pages

### PR DESCRIPTION
**Pull request by toy**
Images optimised using [image_optim](https://github.com/toy/image_optim) v0.19 with following commands:
```sh
image_optim -r images/image_optim --jpegtran-jpegrescan=true
image_optim -r images/image_optim-lossy --jpegtran-jpegrescan=true --allow-lossy
```
Full disclosure: I am the main developer of image_optim :)

### CODE REVIEW

**Comment by JamieMason** [comment]
Still on the list @toy, the complication is that I've moved this to https://github.com/JamieMason/image-optimisation-tools-comparison and need to port it over, then integrate that back with this project.

**Comment by toy** [comment]
Please tell me if I can help.

**Comment by JamieMason** [comment]
Applying this PR over there would be a huge help as that's what I would be needing to do. Apologies for the extra work in this, I didn't expect any PRs for the stats but am grateful that you have.

**Comment by toy** [comment]
Mostly done - [add-image_optim](https://github.com/toy/image-optimisation-tools-comparison/tree/add-image_optim), but I have a problem with generated jsons as I am getting slightly different `meanErrorSquared` and associated `qualityLossPercent` for existing results like:
```diff
       "type": "jpeg",
-      "meanErrorSquared": 13.6704,
-      "qualityLossPercent": 9.080848406746336,
+      "meanErrorSquared": 13.6705,
+      "qualityLossPercent": 9.080914833832644,
       "size": 91031,
@@ -7352,7 +8976,7 @@
       "type": "jpeg-optimised",
-      "meanErrorSquared": 302.72,
+      "meanErrorSquared": 302.657,
       "qualityLossPercent": 100,
```
This may be due to a different version of ImageMagick. I was able to extract only additions for image_optim but probably it is better to regenerate everything in one environment.

**Comment by JamieMason** [comment]
Thanks @toy, I'll pick this up and re-run the suite.

**Comment by toy** [comment]
Do you need a pull request?

**Comment by JamieMason** [comment]
Should be OK, thanks.

**Comment by JamieMason** [comment]
Sorry for the huge wait, I've done [this](https://github.com/JamieMason/image-optimisation-tools-comparison/commit/dfade91171756e38b1f701569ba5069646f3e669) tonight and will be making a front-end to display [this new json](https://github.com/JamieMason/image-optimisation-tools-comparison/blob/master/results/images.json) as soon as I can.

I'll close this PR, please open anything you'd like me to pick up over in the https://github.com/JamieMason/image-optimisation-tools-comparison repo - thanks a lot.

**Comment by toy** [comment]
Sure, thanks!

**Comment by JamieMason** [comment]
_Finally_ @toy it's up there, I need to check things over properly but please see http://jamiemason.github.io/image-optimisation-tools-comparison/ — if the figures are correct, congratulations, image_optim is performing brilliantly!

**Pull request closed without merging**
