### PR TITLE
Update `nexe` to 2.0.0-rc.30.

### PR DESCRIPTION
**Pull request by reitermarkus**
## Types of Changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

* [ ] **feat**: A new feature
* [x] **fix**: A bug fix
* [ ] **docs**: Documentation only changes
* [ ] **style**: Changes that do not affect the meaning of the code
* [ ] **refactor**: A code change that neither fixes a bug or adds a feature
* [ ] **perf**: A code change that improves performance
* [ ] **test**: Adding missing tests
* [ ] **chore**: Changes to the build process or auxiliary tools/libraries

## Description

Fixes build when `stdin` is not a TTY.

## Related Issues

https://github.com/nexe/nexe/pull/496
https://github.com/Homebrew/homebrew-core/pull/28873.

## Justification

– " –

## How Can This Be Tested?

Build with `printf '' | npm run build` and then try using `./dist/imageoptim -V`. The output will be empty before this fix.

### CODE REVIEW

**Comment by ilovezfs** [comment]
doesn't the package-lock.json file need updating too?

**Comment by reitermarkus** [comment]
> doesn't the package-lock.json file need updating too?

Right. I updated the file via GitHub.

**Comment by ilovezfs** [comment]
🎉

**Comment by JamieMason** [comment]
I don't mind doing that when I merge it, thanks a lot.

**Comment by JamieMason** [comment]
@reitermarkus out of interest, does this update contain anything in particular that you need?

**Comment by ilovezfs** [comment]
@JamieMason see https://github.com/Homebrew/homebrew-core/pull/28873. The upgrade was needed in order to get a non-broken build on our Jenkins CI. Otherwise, despite a seemingly successful build the program would just output nothing.

**Comment by ilovezfs** [comment]
@JamieMason on a related note, you may want to add `brew install imageoptim-cli` as a suggested way of installing! :)

**Comment by JamieMason** [comment]
see #18 @ilovezfs, we tried that a while back but no dice. This PR should be merged soon.

**Comment by ilovezfs** [comment]
@JamieMason but now you have dice! I have merged `imageoptim-cli` into Homebrew/homebrew-core already. See
https://github.com/Homebrew/homebrew-core/commit/ad3ec7905f3bfb9c64cc5eb16a5753cef78d15cd
https://github.com/Homebrew/homebrew-core/commit/abca9752a87c50cf5e815e44eefac80dbe2db573

**Comment by JamieMason** [comment]
ha, no way! 😆 thanks @ilovezfs I'll go check that out after I've done this release.

/cc @jamesstout

**Comment by ilovezfs** [comment]
@JamieMason you're welcome. It was really @reitermarkus's doing!

**Comment by JamieMason** [comment]
👏 @reitermarkus 👏 @ilovezfs 👏 

Love it, nice one!

**Comment by JamieMason** [comment]
Just published imageoptim-cli@2.0.3 by the way, thanks a lot

**Comment by ilovezfs** [comment]
Voilà https://github.com/Homebrew/homebrew-core/pull/28978

**Comment by JamieMason** [comment]
👌

**Comment by jamesstout** [comment]
Excellent. thank you.

**Pull request closed without merging**
