### PR TITLE
Added -m / --min-quality parameter for pngquant

### PR DESCRIPTION
**Pull request by fbbarros**
Added -m / --min-quality parameter for pngquant replacing hard coded minimum value.
This is extremely useful to ensure maximum compression in cases where end quality is not an issue.

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks a lot for this. I will pick it up as soon as I can, but it may be a week or two.

**Comment by fbbarros** [comment]
You're very much welcome :)
Take whatever time you need and thank you for the quick feedback :+1:

**Comment by JamieMason** [comment]
@fbbarros this is brilliant! sorry for such a long wait — this is _finally in develop and will be released soon with some other changes.

**Comment by JamieMason** [comment]
Released in imageoptim-cli@1.14.8, thanks so much for taking time to help out.

**Pull request closed without merging**
