### PR TITLE
"verbose" flag to turn on per-file reporting

### PR DESCRIPTION
**Pull request by nwtn**
Part of workaround for
https://github.com/JamieMason/grunt-imageoptim/issues/19

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks for this @nwtn, I'm working on a v2 locally and this will be part of that.

**Comment by nwtn** [comment]
Awesome!

**Comment by JamieMason** [comment]
Sorry for the wait (474 days!) this is _finally in develop and will be released soon with some other changes.

Thanks @nwtn.

**Comment by nwtn** [comment]
awesome :tada:
no need to apologize for the wait. thanks for a bad-ass project and all the work you do.

**Comment by JamieMason** [comment]
Released in imageoptim-cli@1.14.8, thanks so much for taking time to help out.

**Pull request closed without merging**
